definition:
  path: /v1/acord/application
  verb: put
  id: imported#/v1/acord/application#put
  operationId: acordUpdateApplicationV1
  tags:
    - Acord
  parameters:
    - in: header
      name: coresuite-datasource-key
      description: ""
      required: false
      schema:
        type: string
    - in: header
      name: coresuite-user-name
      description: ""
      required: false
      schema:
        type: string
  requestBody:
    description: Request body example
    content:
      application/json:
        schema:
          $ref: "#/components/schemas/acordApplicationV1"
  responses:
    "200":
      description: Response body example
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/acordApplicationV1"
        application/xml:
          schema:
            $ref: "#/components/schemas/acordApplicationV1"
    "400":
      description: Response body example
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errorHandlingV1"
        application/xml:
          schema:
            $ref: "#/components/schemas/errorHandlingV1"
    "404":
      description: Response body example
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errorHandlingV1"
        application/xml:
          schema:
            $ref: "#/components/schemas/errorHandlingV1"
    "500":
      description: Response body example
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errorHandlingV1"
        application/xml:
          schema:
            $ref: "#/components/schemas/errorHandlingV1"
  security:
    - bearerAuth: []
flow: acordUpdateApplicationV1.yaml
method: put
path: /v1/acord/application
errorHandlers: []
handlers: []
