definition:
  path: /v1/policies/{policy_id}/applications/statuses
  verb: get
  id: imported#/v1/policies/{policy_id}/applications/statuses#get
  operationId: getApplicationStatusV1
  tags:
    - Policy
  parameters:
    - in: query
      name: externalPolicyIdIndicator
      description: ""
      required: false
      schema:
        type: boolean
        default: false
    - in: query
      name: effectiveDate
      description: Effective Date
      required: false
      schema:
        type: string
    - in: path
      name: policy_id
      description: Policy Number
      required: true
      schema:
        type: string
    - in: header
      name: coresuite-datasource-key
      description: ""
      required: false
      schema:
        type: string
    - in: header
      name: coresuite-user-name
      description: ""
      required: false
      schema:
        type: string
  requestBody: {}
  responses:
    "200":
      description: Response body example
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/applicationStatusV1"
        application/xml:
          schema:
            $ref: "#/components/schemas/applicationStatusV1"
  security:
    - bearerAuth: []
flow: getApplicationStatusV1.yaml
method: get
path: /v1/policies/{policy_id}/applications/statuses
errorHandlers: []
handlers: []
