definition:
  path: /v1/policies/{policy_id}/applications/statuses
  verb: put
  id: imported#/v1/policies/{policy_id}/applications/statuses#put
  operationId: updateApplicationStatusV1
  tags:
    - Policy
  parameters:
    - in: query
      name: externalPolicyIdIndicator
      description: ""
      required: false
      schema:
        type: boolean
        default: false
    - in: path
      name: policy_id
      description: Policy Number
      required: true
      schema:
        type: string
    - in: header
      name: coresuite-datasource-key
      description: ""
      required: false
      schema:
        type: string
    - in: header
      name: coresuite-user-name
      description: ""
      required: false
      schema:
        type: string
  requestBody:
    description: Request body example
    content:
      application/json:
        schema:
          $ref: "#/components/schemas/applicationStatusV1"
  responses:
    "200":
      description: Response body example
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/applictionStatusResponseV1"
        application/xml:
          schema:
            $ref: "#/components/schemas/applictionStatusResponseV1"
  security:
    - bearerAuth: []
flow: updateApplicationStatusV1.yaml
method: put
path: /v1/policies/{policy_id}/applications/statuses
errorHandlers: []
handlers: []
