definition:
  path: /v1/policy/getApplicationDefaults
  verb: post
  id: imported#/v1/policy/getApplicationDefaults#post
  operationId: f60734e9-11ad-40f7-8b0e-814055268539V1
  tags:
    - Policy
  parameters:
    - in: header
      name: coresuite-datasource-key
      description: coresuite-datasource-key
      required: true
      schema:
        type: string
    - in: header
      name: coresuite-user-name
      description: coresuite-user-name
      required: false
      schema:
        type: string
  requestBody:
    description: Request body example
    content:
      application/json:
        schema:
          $ref: "#/components/schemas/createQuickApplicationRequestV1"
  responses:
    "200":
      description: ""
      content:
        application/json:
          schema:
            type: object
            example: {}
        application/xml:
          schema:
            type: object
            example: {}
  security:
    - bearerAuth: []
flow: f60734e9-11ad-40f7-8b0e-814055268539V1.yaml
method: post
path: /v1/policy/getApplicationDefaults
errorHandlers: []
handlers: []
