definition:
  path: /v1/policies/{policy_id}/application
  verb: put
  id: imported#/v1/policies/{policy_id}/application#put
  operationId: updateApplicationV1
  tags:
    - Policy
  parameters:
    - in: path
      name: policy_id
      description: Policy Number
      required: true
      schema:
        type: string
    - in: header
      name: coresuite-datasource-key
      description: ""
      required: false
      schema:
        type: string
    - in: header
      name: coresuite-user-name
      description: ""
      required: false
      schema:
        type: string
  requestBody:
    description: Request body example
    content:
      application/json:
        schema:
          $ref: "#/components/schemas/applicationV1"
  responses:
    "200":
      description: Response body example
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/NewApplicationResultV1"
        application/xml:
          schema:
            $ref: "#/components/schemas/NewApplicationResultV1"
  security:
    - bearerAuth: []
flow: updateApplicationV1.yaml
method: put
path: /v1/policies/{policy_id}/application
errorHandlers: []
handlers: []
