tags:
  - Policy
sampleInputSchema: ""
sampleData:
  externalPolicyIdIndicator: boolean
  policy_id: string
  commencementDate:
    type: string
    format: date
description: Created by imported openApi schema
steps:
  - name: JSONATA MAP
    stepType: jsonata
    condition: ""
    config:
      maps:
        - jsonata: $
          targetPath: requestBody
    description: mapping request body
  - name: AJV
    stepType: ajv
    condition: ""
    config:
      dataPath: requestBody
      schema:
        commencementDate:
          type: string
          format: date
      targetPath: validations
      error: true
    description: validating request body
  - name: JSONATA MAP
    stepType: jsonata
    condition: ""
    config:
      maps:
        - jsonata: '{"externalPolicyIdIndicator":"externalPolicyIdIndicator"}'
          targetPath: queryParams
    description: mapping query params
  - name: REST
    stepType: rest-new
    condition: "{{validations && validations.length === 0}}"
    config:
      endpoint:
        url: "{{$env.DYNAMIC_APIS_URL}}/policies/{{policy_id}}/commencement-date"
        method: PUT
      restRequest: JSON
      json: "{{requestBody}}"
      queryParams: "{{queryParams}}"
      headers:
        CoreSuite-DataSource-Key: "{{$headers.CoreSuite-DataSource-Key}}"
        CoreSuite-User-Name: "{{$headers.CoreSuite-User-Name}}"
      targetPath: result
    description: ""
