tags:
  - Client
sampleInputSchema: ""
sampleData:
  externalClientIdIndicator: boolean
  effectiveDate: string
  client_id: string
  entityItems:
    type: array
    items:
      properties:
        number:
          type: number
        value:
          type: string
      type: object
description: Created by imported openApi schema
steps:
  - name: JSONATA MAP
    stepType: jsonata
    condition: ""
    config:
      maps:
        - jsonata: $
          targetPath: requestBody
    description: mapping request body
  - name: AJV
    stepType: ajv
    condition: ""
    config:
      dataPath: requestBody
      schema:
        entityItems:
          type: array
          items:
            properties:
              number:
                type: number
              value:
                type: string
            type: object
      targetPath: validations
      error: true
    description: validating request body
  - name: JSONATA MAP
    stepType: jsonata
    condition: ""
    config:
      maps:
        - jsonata: '{"externalClientIdIndicator":"externalClientIdIndicator","effectiveDate":"effectiveDate"}'
          targetPath: queryParams
    description: mapping query params
  - name: REST
    stepType: rest-new
    condition: "{{validations && validations.length === 0}}"
    config:
      endpoint:
        url: "{{$env.DYNAMIC_APIS_URL}}/clients/{{client_id}}/entity-items"
        method: PUT
      restRequest: JSON
      json: "{{requestBody}}"
      queryParams: "{{queryParams}}"
      headers:
        coresuite-datasource-key: "{{$headers.coresuite-datasource-key}}"
        coresuite-user-name: "{{$headers.coresuite-user-name}}"
      targetPath: result
    description: ""
